#!/usr/bin/env sh

case "$1" in
  "window")
    rofi -show window -theme-str "#prompt { enabled: false; } #textbox-prompt-colon {str: \"📌\";}"
    ;;
  "calc")
    rofi -show calc -theme-str "#prompt { enabled: false; } #textbox-prompt-colon {str: \"💯\";}"
    ;;
  "drun")
    rofi -show drun -theme-str "#prompt { enabled: false; } #textbox-prompt-colon {str: \"🤖\";}"  -no-sort
    ;;
  "run")
    rofi -show run -theme-str "#prompt { enabled: false; } #textbox-prompt-colon {str: \"👻\";}"  -no-sort
    ;;
esac
