#!/bin/sh

if [ $# -eq 0 ]; then
    dir=`pwd`
else
    dir=$1
fi

FILES=""
# wrap each argument in the code required to call tangle on it
for i in `ls | grep \.org`; do
    FILES="$FILES \"$i\""
done

read -r -d '' TANGLE <<EOF
(progn
     (require 'org)
     (require 'ob)
     (require 'ob-tangle)
     (mapc (lambda (file)
             (find-file (expand-file-name file "$dir"))
             (org-babel-tangle)
             (kill-buffer))
           '($FILES)))
EOF

emacs -Q --batch --eval "$TANGLE"
